### ISSUE TITLE
For Minecraft 1.7.10

### ISSUE THREAD

**Issue by vlad1vv1** [ToroCraft/Minecoprocessors#6]
Hi, Can do at 1.7.10, please? I would like to make the server on 1.7.10, the servers for 1.10.2 or 1.11 still work poorly and are too heavy for some users.

**Comment by frodare** [comment]
I am going to close this issue because I don't think anyone will ever get around to doing it, it's a lot of work.  The other two suggestions being worked on.  You can now add titles to your processors (visible in the GUI) and the code book item should be going in soon.  Thanks again for the suggestions!
